describe('Crear una cuenta', () => {
  it('Test case 1', () => {
      cy.visit('https://vps-3696213-x.dattaweb.com/')
      cy.contains('Login').should('be.visible').click()
      cy.title('eq', 'Ticketazo')
      cy.contains('¿Queres crear tus eventos?').should('be.visible').click()
      cy.fixture('crearEvento').then((registrar_cliente) => {
      cy.get('[data-cy="input-razon-social"]').type(registrar_cliente.razon_social)
      cy.get('[data-cy="input-cuit"]').type(registrar_cliente.cuit)
      cy.get('[data-cy="select-provincia"]').click().type(registrar_cliente.provincia)
      cy.contains('.cursor-pointer', 'Buenos Aires').click()
      cy.get('[data-cy="select-localidad"]').click().type(registrar_cliente.localidad)
      cy.contains('.cursor-pointer', 'González Moreno').click()
      cy.get('[data-cy="input-direccion"]').type(registrar_cliente.direccion)
      cy.get('[data-cy="input-telefono"]').type(registrar_cliente.telefono)
      cy.get('[data-cy="input-email"]').type(registrar_cliente.email)
      cy.get('[data-cy="input-confirmar-email"]').type(registrar_cliente.confirmar_email)
      cy.get('[data-cy="input-password"]').type(registrar_cliente.contrasena)
      cy.get('[data-cy="input-repetir-password"]').type(registrar_cliente.repetir_contrasena)
      cy.contains('Cuento con establecimiento propio').should('be.visible')
      cy.get('[data-cy="switch-establecimiento"] > .font-inherit').check()
      cy.get('[data-cy="switch-establecimiento"] > .font-inherit').uncheck()
      cy.contains('button', /registrarse/i).click()
      cy.contains('Las contraseñas no coinciden').should('be.visible')
      cy.go(-1)
    })
  })
})
