describe('Crear una cuenta', () => {
  it('Test case 1', () => {
      cy.visit('https://vps-3696213-x.dattaweb.com/')
      cy.contains('Login').should('be.visible').click()
      cy.title('eq', 'Ticketazo')
      cy.contains('¿No tienes cuenta? Registrate!').should('be.visible').click()
      cy.fixture('registrarse').then((datos) => {
      cy.get('[data-cy="input-nombres"]').type(datos.nombres)
      cy.get('[data-cy="input-apellido"]').type(datos.apellido)
      cy.get('[data-cy="input-telefono"]').type(datos.telefono)
      cy.get('[data-cy="input-dni"]').type(datos.dni)
      cy.get('[data-cy="select-provincia"]').click().type(datos.provincia)
      cy.contains('.cursor-pointer', 'Buenos Aires').click()
      cy.get('[data-cy="select-localidad"]').click().type(datos.localidad)
      cy.contains('.cursor-pointer', 'Ciudadela').click()
      cy.get('[data-cy="input-fecha-nacimiento"]').click()
      cy.contains('dd').type('16')
      cy.contains('mm').type('09')
      cy.contains('aaaa').type('1996')
      cy.get('[data-cy="input-email"]').type(datos.email)
      cy.get(':nth-child(9) > .relative > .inline-flex').type(datos.confirmar_email)
      cy.get('[data-cy="input-password"]').type(datos.contrasena)
      cy.get('[data-cy="input-repetir-password"]').type(datos.repetir_contrasena)
      cy.contains('button', /registrarse/i).click()
      cy.wait(3000)
      cy.go(-1)
    })
  })
})
